/**
 * ESLint configuration.
 *
 * CLAUDE.md §27 requires lint and format scripts; this is the lint half.
 *
 * ## What this is tuned for
 *
 * Telga is a money-handling codebase whose invariants are enforced by tests
 * and by the type system rather than by convention. So the rules here are the
 * ones that catch **classes of mistake the tests cannot**:
 *
 *   - a floating promise, which in this codebase means a ledger write nobody
 *     waited for (CLAUDE.md §13: every debit has a matching credit — an
 *     un-awaited posting breaks that silently);
 *   - `any`, which erases the branded ids and `Money` that stop a merchant id
 *     being passed where a transaction id belongs;
 *   - unused code, which is usually a half-finished change.
 *
 * Purely stylistic rules are left to Prettier. A linter that argues about
 * quote marks trains people to ignore it, and this one has to be worth
 * reading when it fires.
 *
 * ## Why type-aware linting is on
 *
 * `no-floating-promises` and `no-misused-promises` need type information to
 * work at all, and those two are the point. It costs a slower lint run.
 */

import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Build output, dependencies, and the vault. Linting generated `.js` next
    // to its source would report every finding twice.
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'docs/**',
      'coverage/**',
      '*.config.js',
      'scripts/**/*.mjs',
      // Config and standalone scripts sit outside the TypeScript project, so
      // type-aware linting cannot parse them — and they are not application code.
      '*.config.ts',
      '**/*.cjs',
      'apps/merchant-pos/assets/**',
      // Obsidian's own plugin bundles. Vendor JavaScript that ships with the
      // vault, not Telga source — and not in any tsconfig, so type-aware
      // linting cannot parse it anyway.
      '.obsidian/**',

      // The generated Android project and everything Capacitor copies into it.
      //
      // `apps/mobile/android/` is scaffolded by Capacitor and rewritten by
      // `cap sync`; `www/config.js` is generated by `mobile:configure`. None of
      // it is in a tsconfig, so type-aware linting cannot parse it, and none of
      // it is hand-written Telga source. `www/connect.js` is the one exception
      // that *is* hand-written — it is deliberately a plain browser script with
      // no module syntax, because the page loads it with a <script> tag and the
      // APK ships it byte-for-byte. Its behaviour is covered by
      // tests/mobile/connect.test.ts, which is linted.
      'apps/mobile/android/**',
      'apps/mobile/www/*.js',
      'apps/mobile/capacitor.config.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // --- the rules that matter here ------------------------------------
      //
      // An un-awaited promise in this codebase is a ledger write nobody
      // waited for. Error, not warning.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // `any` erases the branded ids and `Money` that stop a merchant id
      // being passed where a transaction id belongs.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',

      // Half-finished changes.
      '@typescript-eslint/no-unused-vars': [
        'error',
        // A leading underscore is how this codebase already marks a parameter
        // that exists to satisfy an interface — see `cardPurchase.ts`.
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // Comparing against `null` or `undefined` loosely is how an absent
      // balance becomes a zero one.
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      // --- deliberately off ------------------------------------------------
      //
      // `require-await` is wrong about this codebase. Every one of its 26
      // findings is a method implementing a port whose interface returns a
      // `Promise` — `AirtimeProvider.submit`, `.getStatus`, `.reverse`,
      // `CardReader.read`, `PaymentProcessor.authorize`. The simulator answers
      // synchronously; a real adapter will not. Marking those `async` is the
      // whole point of the port: the caller must be written to await, so that
      // swapping the simulator for a network client is not a rewrite. Dropping
      // `async` to satisfy the rule would make the simulator's signature a lie
      // about the contract it implements.
      '@typescript-eslint/require-await': 'off',

      // Prettier owns formatting. A linter that argues about quote marks
      // trains people to ignore it.
      '@typescript-eslint/no-non-null-assertion': 'off',
      // The codebase uses template literals for embedded CSS and JS, where
      // this rule fires constantly and says nothing.
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },

  {
    // Tests reach into internals on purpose — that is what makes them able to
    // prove an invariant rather than only observe a screen.
    files: ['tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
    },
  },
);
