/**
 * Recording a merchant application, and bounding who may record one.
 *
 * ## Why this exists rather than a second copy of the console's SQL
 *
 * Until 2026-09-09 exactly one caller wrote `merchant_applications`: the
 * operations console's `POST /applications`, with the insert, the document
 * loop and the transaction spelled out inline. **D138** adds a second caller —
 * the app's own *Register as vendor* — and two hand-written copies of an
 * intake write is how the two drift: one gains a validation the other does not,
 * one wraps its documents in the transaction and the other does not, and the
 * difference is discovered by a shop whose papers vanished.
 *
 * So the write lives here once, and both callers pass through it. The console
 * keeps its screens and its audit event; the app keeps its own; neither owns
 * the SQL.
 *
 * ## The transaction boundary is not negotiable
 *
 * The console's own comment records what happened when it was not one: the
 * application row was written first and the documents after it, so a document
 * that collided on the unique `(kind, reference)` index left the application
 * behind — *a shop in the review queue with no papers, created by the very
 * check meant to refuse it*. A duplicate TIN is the case that index exists for,
 * so it is the case least able to afford a half-written record.
 *
 * `storeDocument` is called **inside** the transaction for the same reason the
 * console called it there: a database failure after the bytes are written
 * leaves an unreferenced file, which is a tidy-up, while the reverse leaves a
 * row promising a passport that is not there, which is a gap in the evidence.
 */

import type { Db } from '../sqlite/connection';

/** Who typed the application in. See migration 018 — this is about evidence. */
export type SubmissionChannel = 'ADMIN' | 'SELF_SERVICE';

export interface ApplicationDocumentInput {
  /**
   * Generated by the caller, not here.
   *
   * Every other id in this system comes from the injected `newId`, so that a
   * test can make them deterministic. Deriving one from the application id
   * would quietly opt this table out of that.
   */
  readonly id: string;
  readonly kind: string;
  readonly reference: string;
  /** ISO timestamp, or absent for a document that does not lapse. */
  readonly expiresAt?: string;
  /** The stored ciphertext handle, when a scan accompanied the reference. */
  readonly documentUri?: string;
  readonly mediaType?: string;
  readonly byteSize?: number;
  /**
   * Store the scan, and say where it went — called **inside** the transaction.
   *
   * The console encrypts an uploaded document to the volume as each row is
   * written, and the ordering is deliberate: a database failure after the bytes
   * are written leaves an unreferenced file, which is a tidy-up, while the
   * reverse leaves a row promising a passport that is not there, which is a gap
   * in the evidence. Passing the store as a callback is what lets that ordering
   * survive being moved out of the console.
   *
   * Absent for a document with no scan — the app's own registration form takes
   * reference numbers only.
   */
  readonly resolve?: () =>
    | { readonly documentUri: string; readonly mediaType: string; readonly bytes: number }
    | undefined;
}

export interface ApplicationInput {
  readonly id: string;
  readonly reference: string;
  readonly submittedVia: SubmissionChannel;
  readonly legalName: string;
  readonly ownerName: string;
  readonly phone: string;
  readonly email?: string;
  readonly address: string;
  readonly locality: string;
  readonly at: string;
  readonly documents: readonly ApplicationDocumentInput[];
}

/** Why an application could not be written. Distinguished, because they differ. */
export type ApplicationWriteRefusal =
  /** A licence or TIN already recorded against another shop. A finding, not a typo. */
  | 'DOCUMENT_ALREADY_REGISTERED_TO_ANOTHER_SHOP'
  /** Anything else the database refused. */
  | 'REGISTRATION_NOT_SAVED';

export class ApplicationWriteError extends Error {
  constructor(readonly refusal: ApplicationWriteRefusal) {
    super(`The application was not recorded: ${refusal}.`);
    this.name = 'ApplicationWriteError';
  }
}

/**
 * Write one application and its documents, or write nothing at all.
 *
 * Throws {@link ApplicationWriteError}. The caller decides what to show; this
 * decides only that the two outcomes are all-or-nothing.
 */
export function recordApplication(db: Db, input: ApplicationInput): void {
  db.prepare('BEGIN').run();
  try {
    db.prepare(
      `INSERT INTO merchant_applications
         (id, reference, status, submitted_via, legal_name, owner_name, phone, email,
          address, locality, submitted_at, created_at, updated_at)
       VALUES (?, ?, 'SUBMITTED', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    ).run(
      input.id,
      input.reference,
      input.submittedVia,
      input.legalName.trim(),
      input.ownerName.trim(),
      input.phone.trim(),
      (input.email ?? '').trim().length > 0 ? (input.email ?? '').trim() : null,
      input.address.trim(),
      input.locality.trim(),
      input.at,
      input.at,
      input.at,
    );

    for (const document of input.documents) {
      const stored = document.resolve?.();
      db.prepare(
        `INSERT INTO merchant_application_documents
           (id, application_id, kind, reference, status, expires_at,
            document_uri, media_type, byte_size, created_at, updated_at)
         VALUES (?, ?, ?, ?, 'SUPPLIED', ?, ?, ?, ?, ?, ?)`,
      ).run(
        document.id,
        input.id,
        document.kind,
        document.reference.trim(),
        (document.expiresAt ?? '').length > 0 ? document.expiresAt : null,
        stored?.documentUri ?? document.documentUri ?? null,
        stored?.mediaType ?? document.mediaType ?? null,
        stored?.bytes ?? document.byteSize ?? null,
        input.at,
        input.at,
      );
    }
    db.prepare('COMMIT').run();
  } catch (error) {
    // Nothing is left behind: no application, no partial set of documents.
    db.prepare('ROLLBACK').run();
    const duplicate = /UNIQUE constraint failed/.test(
      error instanceof Error ? error.message : '',
    );
    throw new ApplicationWriteError(
      duplicate ? 'DOCUMENT_ALREADY_REGISTERED_TO_ANOTHER_SHOP' : 'REGISTRATION_NOT_SAVED',
    );
  }
}

// --- the throttle -----------------------------------------------------------

/**
 * Count what one source has tried recently.
 *
 * Both outcomes count. A refused submission that did not count would let a
 * caller probe the validator for free and be limited only on the attempts that
 * succeeded — which is the opposite of what a throttle is for.
 */
export function countRegistrationAttemptsSince(db: Db, source: string, since: string): number {
  const row = db
    .prepare(
      'SELECT COUNT(*) AS n FROM registration_attempts WHERE source = ? AND created_at > ?',
    )
    .get(source, since) as { n: number };
  return row.n;
}

export function recordRegistrationAttempt(
  db: Db,
  source: string,
  outcome: 'RECORDED' | 'REFUSED',
  at: string,
): void {
  db.prepare(
    'INSERT INTO registration_attempts (source, outcome, created_at) VALUES (?, ?, ?)',
  ).run(source, outcome, at);
}

/**
 * Forget attempts older than the window needs.
 *
 * §24's retention rule applied to the one table that accumulates a row per
 * anonymous request. Nothing here is evidence of anything after the window
 * closes, so keeping it would be collection without a purpose.
 */
export function pruneRegistrationAttempts(db: Db, before: string): number {
  const result = db
    .prepare('DELETE FROM registration_attempts WHERE created_at <= ?')
    .run(before);
  return result.changes;
}
