/**
 * The bilingual string table.
 *
 * `04 UX UI/English Strings.md` and `04 UX UI/Amharic Strings.md` are the
 * authoritative sources; this file is their machine-readable form, and
 * `tests/ui/localization.test.ts` fails if the two drift apart.
 *
 * ## Amharic status
 *
 * Every Amharic value here is a **draft**. It carries the same warning the
 * vault note carries — REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION — and
 * none of it has been through that review.
 *
 * Fourteen keys have **no Amharic at all**: the screen titles and
 * `support.response.notice`. They are absent rather than machine-translated,
 * because an unreviewed guess that looks finished is worse than a visible gap.
 * `translate` falls back to English and says that it did.
 */

export const LOCALES = ['en', 'am'] as const;
export type Locale = (typeof LOCALES)[number];

export const DEFAULT_LOCALE: Locale = 'en';

/** English is complete by definition: it is the source language. */
export const EN = Object.freeze({
  'sale.action.sell_airtime': 'Sell airtime',
  'sale.amount.select': 'Select amount',
  'sale.confirm.action': 'Confirm sale',
  'status.processing': 'Processing',
  'status.pending': 'Transaction pending',
  'status.pending.do_not_retry': 'Do not retry yet',
  'status.successful': 'Transaction successful',
  'status.failed': 'Transaction failed',
  'status.under_review': 'Under review',
  'status.provider_unavailable': 'Provider temporarily unavailable',
  'status.sales_unavailable': 'Sales temporarily unavailable',
  'status.no_charge': 'No charge was made',
  'balance.available': 'Available balance',
  'balance.reserved': 'Reserved balance',
  'balance.under_review': 'Under review balance',
  'commission.net': 'Net commission',
  'receipt.reprint': 'Reprint receipt',
  'transaction.id': 'Transaction ID',
  'support.contact': 'Contact support',
  'mode.training': 'Training mode — no real value',
  'status.pending.message': 'This transaction is still being checked. Do not retry yet.',
  'status.under_review.message':
    'This transaction is being reviewed. Your balance is protected while we check with the provider.',
  'status.failed.message': 'This sale did not go through. No charge was made.',
  'status.provider_unavailable.message':
    'Airtime is temporarily unavailable from this provider. No charge was made. Other services are still working.',
  'status.offline.message':
    'Sales are temporarily unavailable. You can still view history, reports and support.',
  'receipt.reprint.notice': 'This is a reprint. It is not a new sale.',
  'support.response.notice':
    'We will give you a first answer straight away and a final answer within 24 hours.',
  'funding.simulated.notice': 'This is a simulated funding submission. No real money is involved.',
  'error.validation.recipient': 'Check the phone number and try again.',
  'error.balance.insufficient': 'Not enough available balance for this sale.',
  'error.permission.denied': 'Your role does not allow this action.',
  'error.session.expired': 'Your session has ended. Sign in again. Nothing was lost.',
  'error.printer.failed': 'The receipt did not print. The sale is complete — you can reprint it.',
  'error.duplicate.blocked': 'This sale is already in progress. Do not start it again.',
  // A poll that never reached the server. Distinct from an error the server
  // sent back: nothing is known about the sale, so the text must not imply
  // either outcome.
  'error.network_unavailable':
    'Telga could not be reached. The result of this sale is not known yet — do not retry it.',
  'screen.login': 'Sign in',
  'screen.home': 'Home',
  'screen.provider_select': 'Select network',
  'screen.amount_select': 'Select amount',
  'screen.recipient': 'Customer cellphone number',
  'screen.confirm': 'Confirm sale',
  'screen.balance': 'Balance',
  'screen.search': 'Find transaction',
  'screen.details': 'Transaction details',
  'screen.reports': 'Reports',
  'screen.funding': 'Add funds',
  'screen.support': 'Support',
  'screen.admin_queue': 'Review queue',
  'screen.menu': 'Main menu',
  'screen.vouchers': 'Vouchers',
  'screen.product_type': 'Select product type',
  'screen.order_details': 'Order details',
  'screen.pin_auth': 'PIN authorization',
  'screen.voucher_result': 'Training voucher result',
  'screen.launcher': 'Telga',
  'screen.pay_settings': 'Telga Pay settings',
  'statements.title': 'Statement',
  'statements.from': 'From',
  'statements.to': 'To',
  'statements.apply': 'Apply',
  'statements.clear': 'Clear',
  'statements.sales': 'Sales',
  'statements.gross': 'Sold',
  'statements.profit': 'Profit',
  'statements.reversals': 'Reversed',
  'statements.total': 'Total',
  'statements.note': 'Profit is what was earned on each day. Moving profit into the selling balance is not a sale and is not subtracted here; a reversed sale is.',
  'pay.records.transactions_title': 'Telga Pay transactions',
  'pay.records.statements_title': 'Telga Pay statements',
  'pay.records.cards_not_stored': 'Card attempts are not recorded. A simulated card moves no value, so nothing is written to the ledger for one. Training deposits are recorded, because they post a real balanced entry against the float.',
  'pay.records.empty': 'Nothing recorded yet.',
  'pay.records.count': 'Entries',
  'pay.settings.flag_card_note': 'The card simulator. Nothing behind it reaches a bank.',
  'pay.settings.flag_accept_note': 'Real card acceptance. Needs an acquirer and a licence.',
  'pay.settings.flag_deposit_note': 'Simulated deposits into the training float.',
  'pay.settings.flag_cash_note': 'Taking cash in or paying it out. Legal review required.',
  'pay.settings.intro':
    'These settings belong to Telga Pay. Slip width and business details are shared with Telga Vending and are set there.',
  'pay.settings.records': 'Records',
  'pay.settings.transactions': 'Card transactions',
  'pay.settings.statements': 'Card statements',
  'pay.settings.cards': 'Training cards',
  'pay.settings.cards_hint': 'A reference sheet, not a setting. These cards are fixed in the simulator so each outcome can be practised on demand.',
  'pay.settings.flags': 'What is switched on',
  'pay.settings.flag_on': 'On',
  'pay.settings.flag_off': 'Off',
  'pay.settings.slips': 'Slips',
  'pay.settings.slips_note': 'Slip width, the advertisement line and the business details print on every Telga slip, card or voucher. They are one shop identity and are set in Telga Vending settings.',
  'pay.settings.account': 'Signed in as',
  'pay.settings.operator': 'Operator',
  'pay.settings.device': 'Device',
  'pay.settings.merchant': 'Merchant',
  'settings.slip_size': 'Slip width',
  'screen.launcher_apps': 'Choose Telga service',
  'screen.dashboard': 'Telga dashboard',
  'screen.coming_soon': 'Coming soon',
  'screen.pay_entry': 'Telga Pay',
  'screen.pay_amount': 'Enter amount',
  'screen.pay_card': 'Card simulator',
  'screen.pay_result': 'Payment result',
  'voucher.action.print': 'PRINT',
  'voucher.action.cancel': 'CANCEL',
  'voucher.action.back': 'BACK',
  'voucher.action.continue': 'Continue',
  'voucher.product.airtime': 'Airtime',
  'voucher.data.unavailable': 'Not available in training',
  'voucher.pin.prompt': 'Enter PIN to buy training voucher',
  'voucher.pin.clear': 'Clear',
  'voucher.pin.confirm': 'OK / CONFIRM',
  'voucher.result.no_printer': 'Training voucher shown on screen — no physical printer configured.',
  'voucher.result.preview_notice':
    'Preview only. PIN verification and voucher creation are not yet active — no training voucher was recorded.',
  'voucher.result.new_sale': 'New sale',
  'voucher.amount.invalid': 'Select a valid amount for this network.',
  'sale.amount.select_placeholder': 'Select airtime amount',
  'sale.amount.custom': 'Custom amount',
  'sale.amount.custom_label': 'Amount in birr',
  'sale.amount.custom.below_min': 'That amount is below the training minimum.',
  'sale.amount.custom.above_max': 'That amount is above the training maximum.',
  'sale.amount.custom.not_multiple': 'Enter a whole number of birr.',
  'sale.amount.custom.not_a_number': 'Enter a valid amount.',
  'voucher.pin.heading': 'Confirm transaction PIN',
  'voucher.product.topup': 'Direct top-up',
  'voucher.summary.merchant': 'Training merchant',
  'voucher.summary.amount': 'Amount',
  'voucher.summary.total': 'Total',
  'voucher.summary.profit': 'Your profit',
  'voucher.summary.recipient': 'Phone number',
  'topup.tile.label': 'Top up a phone',
  'topup.phone.label': 'Customer phone number',
  'topup.phone.hint': 'The number the airtime is sent to.',
  'topup.phone.invalid': 'Enter a valid phone number.',
  'topup.phone.required': 'A phone number is required for a direct top-up.',
  'nav.main': 'Main',
  'menu.lock': 'Lock',
  'card.read': 'Read card',
  'card.declined_heading': 'Not approved',
  // Deliberately neither "approved" nor "declined": on a silent bank the
  // money may or may not have moved, and saying either causes a real loss.
  'card.no_response_heading': 'No answer from the bank',
  'card.try_again': 'Ask the customer to try again with the same card.',
  'card.number': 'Card',
  'card.scheme': 'Type',
  'card.entry_mode': 'Read by',
  'card.simulator_title': 'Training card — a real reader supplies this itself',
  'settings.shift.hint': 'A shift records when an operator started and finished. It holds no money of its own.',
  'settings.shift.statement': 'Statement for this shift',
  'settings.account.operator': 'Operator',
  'settings.account.device': 'Device',
  'settings.account.merchant': 'Merchant',
  'settings.account.hint':
    'Telga signs in with an operator ID, a PIN and a device key — there is no password. Use Change PIN below.',
  'outage.heading': 'Service unavailable',
  'outage.unavailable': 'not available right now',
  'outage.no_charge': 'Nothing was charged. No sale was made and no commission was earned.',
  'outage.last_checked': 'Last checked',
  'outage.still_available': 'Still available',
  'offline.heading': 'Telga is not reachable',
  'offline.no_sales': 'No new sales can be made until the connection returns.',
  'offline.no_offline_vending': 'Selling offline is not allowed. Do not take money for a sale this machine cannot complete.',
  'offline.last_seen': 'Last connected',
  'offline.still_available': 'What still works',
  'receipt.lookup_title': 'Shop copy — lookup',
  'receipt.lookup_note': 'Keep this to find the sale again.',
  'dashboard.low_balance': 'Your selling balance is running low. Top up before it runs out.',
  'statements.admin_only': 'Statements are set to owner-only. Ask the shop owner to view them.',
  'card.decline.insufficient_funds': 'Not enough money on the card. Nothing was charged.',
  'card.decline.wrong_pin': 'Wrong card PIN. Ask the customer to try again.',
  'card.decline.expired': 'That card has expired. Nothing was charged.',
  'card.decline.blocked': 'That card is blocked. Nothing was charged.',
  'card.decline.limit': 'That amount is over the card limit. Nothing was charged.',
  'card.decline.issuer': 'The bank did not answer. Try again in a moment.',
  'card.decline.generic': 'The card was declined. Nothing was charged.',
  'card.no_response': 'The bank has not answered. Do not retry and do not hand over goods yet — check the transaction before continuing.',
  'card.not_read': 'The card was not read. Ask the customer to present it again.',
  'card.no_reader': 'No card reader is connected to this device.',
  'card.present': 'Tap, insert or swipe the card',
  'card.approved': 'Approved',
  'card.reference': 'Authorisation',
  'menu.manage': 'Manage',
  'lock.heading': 'Screen locked',
  'lock.pin_label': 'Enter your PIN to unlock',
  'lock.unlock': 'Unlock',
  'lock.wrong': 'That PIN is not correct. The screen stays locked.',
  'menu.open': 'Open menu',
  'menu.statements': 'Statements',
  'menu.end_shift': 'End shift',
  'menu.customers': 'Customer list',
  'menu.learning': 'Learning',
  'menu.settings': 'Settings',
  'menu.help': 'Help',
  'menu.logout': 'Log out',
  'screen.help': 'Telga support',
  'screen.learning': 'How to use Telga',
  'screen.customers': 'Customer list',
  'screen.end_shift': 'End shift',
  'help.intro': 'Telga support, for anything this machine cannot answer.',
  'help.phone': 'Phone',
  'help.email': 'Email',
  'help.hours': 'Hours',
  'help.address': 'Address',
  'help.reference_hint': 'Have the transaction reference from the slip ready — it is the fastest way to find a sale.',
  'learning.intro': 'Each step below is one thing to try on this machine. Work through them in order.',
  'customers.empty': 'No saved customers yet.',
  'customers.name': 'Customer name',
  'customers.phone': 'Phone number',
  'customers.add': 'Save customer',
  'customers.privacy': 'Saved numbers are stored masked, the same way a slip prints them.',
  'customers.invalid': 'Enter a name and a valid phone number.',
  'shift.open_since': 'Shift open since',
  'shift.none_open': 'No shift is open.',
  'shift.end': 'End shift',
  'shift.end_confirm': 'End this shift?',
  'shift.ended': 'Shift ended.',
  'settings.section.shift': 'Shift settings',
  'settings.section.account': 'Account settings',
  'settings.section.app': 'In-app settings',
  'settings.section.admin': 'Admin only',
  'settings.section.security': 'Security',
  'settings.section.about': 'About and policies',
  'settings.toggle.sound': 'Play sound',
  'settings.toggle.hide_balance': 'Hide Telga balance',
  'settings.toggle.low_balance': 'Alert me when balance is low',
  'settings.toggle.statements_admin': 'Statements viewable by admin only',
  'settings.toggle.print_barcode': 'Print barcode on slips',
  'settings.toggle.print_lookup': 'Print lookup slip',
  'settings.toggle.pin_lock': 'Require PIN to unlock',
  'settings.lock_seconds': 'Lock the screen after (seconds)',
  'settings.account.phone': 'Change phone number',
  'settings.account.password': 'Change password',
  'settings.account.details': 'Change your details',
  'settings.about.telga': 'About Telga',
  'settings.about.terms': 'Terms and conditions',
  'settings.about.privacy': 'Privacy policy',
  'settings.about.cookies': 'Cookie policy',
  'settings.back': 'Back',
  'balance.top_up': 'Top up your balance',
  'balance.top_up.open': 'Add to balance',
  'balance.top_up.bank': 'Bank deposit',
  'balance.top_up.pay': 'Telga Pay balance',
  'balance.top_up.profit': 'Profit',
  'screen.profit_transfer': 'Move profit to selling balance',
  'profit.transfer.action': 'Move to selling balance',
  'profit.transfer.available': 'Profit available to move',
  'profit.transfer.amount_label': 'Amount in birr',
  'profit.transfer.amount_invalid': 'Enter a whole number of birr, at least 1.',
  'profit.transfer.exceeds': 'That is more than the profit you have. Nothing was moved.',
  'profit.transfer.confirm': 'OK',
  'profit.transfer.done': 'Moved to your selling balance.',
  'profit.transfer.remaining': 'Profit remaining',
  'profit.transfer.new_balance': 'New selling balance',
  'profit.transfer.none': 'There is no profit to move yet.',
  'settings.pin.heading': 'Change transaction PIN',
  'settings.pin.current': 'Current PIN',
  'settings.pin.new': 'New PIN',
  'settings.pin.confirm': 'Confirm new PIN',
  'settings.pin.save': 'Change PIN',
  'settings.pin.changed': 'Transaction PIN changed. Use the new PIN from now on.',
  'settings.pin.wrong_current': 'That current PIN is not correct. Nothing was changed.',
  'settings.pin.weak': 'Choose a different six-digit PIN. Avoid 111111 or 123456.',
  'settings.pin.mismatch': 'The two new PINs do not match. Nothing was changed.',
  'settings.business.heading': 'Business details',
  'settings.business.hint': 'Printed on every slip. Telga does not verify these.',
  'settings.business.name': 'Business name',
  'settings.business.address': 'Address',
  'settings.business.phone': 'Shop phone number',
  'settings.business.tin': 'TIN',
  'settings.business.licence': 'Trade licence number',
  'settings.business.footer': 'Closing line on the slip',
  // The launcher's own label. The visible control is the Telga mark, so
  // this is both the cue printed under it and the accessible name a screen
  // reader announces — an operator who cannot see the logo still hears what
  // the button does.
  'launcher.open_telga': 'Tap Telga to open',
  'voucher.quantity.label': 'How many vouchers',
  'voucher.quantity.invalid': 'Choose between 1 and 20 vouchers.',
  'voucher.quantity.decrease': 'One fewer',
  'voucher.quantity.increase': 'One more',
  'voucher.summary.quantity': 'Vouchers',
  'voucher.summary.each': 'Price each',
  'receipt.slip.batch_position': 'Voucher',
  'voucher.action.main': 'MAIN',
  'voucher.action.main_confirm': 'Leave this sale and go to the main screen? No voucher will be issued.',
  'voucher.product.data': 'Data',
  'data.category.select': 'Choose a data type',
  'data.package.select': 'Choose a package',
  'data.column.volume': 'Bundle',
  'data.column.validity': 'Valid for',
  'data.phone.label': 'Customer phone number',
  'data.phone.required': 'A phone number is required for a data bundle.',
  'data.category.monthly': 'Monthly',
  'data.category.weekly': 'Weekly',
  'data.category.daily': 'Daily',
  'data.category.hourly': 'Hourly',
  'data.category.weekend': 'Weekend',
  'data.category.all_access': 'All-Access',
  'data.category.lte': 'LTE',
  'data.category.social': 'Social',
  'data.category.voice': 'Voice',
  'receipt.slip.network_code': 'Network',
  'receipt.slip.voucher_pin': 'Voucher PIN',
  'receipt.slip.token_reference': 'Token reference',
  'receipt.slip.dial_string': 'To load, dial',
  'receipt.slip.simulated_code_notice': 'SIMULATED CODE — will not load airtime',
  'voucher.error.insufficient_balance': 'Insufficient training balance. No voucher was issued.',
  'voucher.error.order_expired': 'This order expired before it was confirmed. No voucher was issued.',
  'voucher.error.order_not_open': 'This order was already completed or cancelled. No voucher was issued.',
  'voucher.error.duplicate': 'This voucher was already issued. It was not issued again.',
  'voucher.error.generic': 'The voucher could not be completed. No voucher was issued.',
  'voucher.result.failed_title': 'Voucher not issued',
  'voucher.action.back_to_vouchers': 'Back to Vouchers',
  'voucher.action.home': 'Home',
  'receipt.not_available': 'No receipt is available for this transaction yet.',
  'receipt.slip.title': 'Transaction slip',
  'receipt.slip.reprint_notice': 'REPRINT — not a new sale',
  'receipt.action.close': 'Close',
  'receipt.action.print': 'Print',
  'receipt.print.failed': 'Printing could not be completed. The transaction is unchanged.',
  'transactions.empty': 'No transactions yet.',
  'transactions.column.datetime': 'Date and time',
  'transactions.column.service': 'Service',
  'transactions.column.amount': 'Amount',
  'transactions.column.status': 'Status',
  'transactions.column.reference': 'Reference',
  'voucher.pin.wrong': 'Incorrect transaction PIN. No voucher was issued.',
  'voucher.pin.locked':
    'Too many incorrect PIN attempts. Voucher authorization is locked for a few minutes. Your login is not affected.',
  'launcher.tile.telga.label': 'TELGA',
  'launcher.tile.telga.subtitle': 'Vending and merchant services',
  'launcher.tile.telgapay.label': 'TELGA PAY',
  'launcher.tile.telgapay.subtitle': 'Card-payment training simulator',
  'dashboard.balance.pill': 'Balance',
  'dashboard.profit.pill': 'Profit',
  'dashboard.profit.unavailable': 'Not yet available',
  'dashboard.service.data': 'Data',
  'dashboard.service.electricity': 'Electricity',
  'dashboard.service.account': 'Account',
  'dashboard.service.water': 'Water',
  'dashboard.service.dstv': 'DStv',
  'dashboard.service.telecom': 'Telecom bill',
  'dashboard.service.traffic': 'Traffic',
  'dashboard.service.lottery': 'Lottery',
  'dashboard.service.tickets': 'Tickets',
  'dashboard.service.fuel': 'Fuel',
  // Four services confirmed by research as still paid manually or through an
  // agent in Ethiopia, added 2026-08-29. Each is COMING_SOON: a tile is a
  // product claim, and none of these has a provider agreement behind it.
  'dashboard.service.internet': 'Internet',
  'dashboard.service.school': 'School fees',
  'dashboard.service.insurance': 'Insurance',
  'dashboard.service.govfees': 'Government fees',
  'dashboard.nav.reprint': 'Re-print',
  'dashboard.coming_soon.message': 'Coming soon — this service is not active in training.',
  'dashboard.nav.prepaid': 'Prepaid',
  'dashboard.nav.payments': 'Payments',
  'dashboard.back_to_launcher': 'Telga launcher',
  'pay.banner': 'Training card-payment simulator — no real processor connected.',
  'pay.no_transactions': 'No Telga Pay transactions recorded in training.',
  'pay.todays_sales_label': "Today's Telga sales",
  'pay.transactions_label': 'Transaction(s)',
  'pay.purchase.label': 'Purchase',
  'pay.cashback.label': 'Cashback',
  'pay.amount.label': 'Amount',
  'pay.note.label': 'Add Note',
  'pay.pay_now': 'Pay Now',
  'pay.card.prompt': 'Please Insert, Swipe or Tap Card',
  'pay.card.tap': 'Tap / Contactless',
  'pay.card.insert': 'Insert / Chip',
  'pay.card.swipe': 'Swipe',
  'pay.card.example_notice':
    'Visa and Mastercard shown as training examples only. No real card network is connected.',
  'pay.outcome.approved': 'Training simulation only — no real payment was processed.',
  'pay.outcome.declined': 'Declined — insufficient simulated funds. No payment was made.',
  'pay.outcome.read_error': 'Card could not be read. Try again or choose another method.',
  'pay.outcome.cancelled': 'Cancelled. No payment was made.',
  'pay.card.practice_heading': 'Practise a different training result',
  'pay.card.practice_declined': 'Declined',
  'pay.card.practice_read_error': 'Card read error',
  'pay.card.practice_cancelled': 'Cancelled',
  'pay.retry': 'Try again',
  'pay.deposit.label': 'Add balance',
  'pay.deposit.heading': 'Add training balance',
  'pay.deposit.prompt': 'How much simulated balance do you want to add?',
  'pay.deposit.confirm': 'Add to balance',
  'pay.deposit.notice':
    'Training only. This adds simulated balance so airtime sales can be practised. No real card is read and no real money moves.',
  'pay.deposit.credited': 'Simulated balance added.',
  'pay.deposit.invalid': 'Enter a valid amount to add.',
  'pay.deposit.slip_title': 'Telga Pay deposit slip',
  'pay.deposit.method': 'Card method',
  'settings.tile.label': 'Settings',
  'settings.heading': 'Slip and training settings',
  'settings.slip_size.label': 'Slip width',
  'settings.slip_size.58': '58 mm (narrow roll)',
  'settings.slip_size.80': '80 mm (wide roll)',
  'settings.advert.label': 'Advertisement line on the slip',
  'settings.advert.hint': 'Printed at the foot of every slip. Leave empty for none.',
  'settings.profit.label': 'Training profit percentage',
  'settings.profit.hint':
    'Training figure only. It is not a negotiated commission and not a production rate.',
  'settings.profit.invalid': 'Enter a percentage between 0 and 100.',
  'settings.save': 'Save settings',
  'settings.saved': 'Settings saved.',
  'settings.permission_denied': 'Only the shop owner can change these settings.',
  'settings.signout': 'Sign out completely',
  'settings.signout.confirm':
    'Sign out completely? This machine will ask for all your sign-in details again.',
  'settings.signout.hint':
    'Signing out here clears the device, the device key and the operator. An idle timeout asks only for the PIN.',
  'receipt.training_notice': 'TRAINING — NO REAL VALUE',

  // --- Register as Telga member (D138) --------------------------------------------
  //
  // Wording rule for this whole block: nothing may read as a sign-up. The
  // applicant is asking to be considered, and every string says so — because
  // the alternative is a shop that believes it has an account and discovers
  // days later that it has a queue position.
  'screen.register': 'Register as Telga member',
  'register.heading': 'Register your shop with Telga',
  'register.intro':
    'Fill this in and Telga will review it. Approval is not automatic, and no account is created yet. If your shop is approved, Telga will contact you with your sign-in details.',
  'register.legal_name': 'Business name',
  'register.legal_name.hint': 'Exactly as it appears on your trade licence.',
  'register.owner_name': 'Owner full name',
  'register.phone': 'Phone number',
  'register.phone.hint': 'Telga will call this number about your application.',
  'register.email': 'Email (optional)',
  'register.email.hint': 'Leave blank if you do not use email.',
  'register.address': 'Shop address',
  'register.locality': 'Town or sub-city',
  'register.documents': 'Your documents',
  'register.documents.hint':
    'Enter the number printed on each document. Do not send photographs here — Telga will check the originals with you.',
  'register.trade_licence': 'Trade licence number',
  'register.trade_licence_expiry': 'Trade licence expiry date',
  'register.tin': 'TIN',
  'register.photo_id': 'Owner ID number',
  'register.photo_id.hint': 'National ID, passport or driving licence.',
  'register.submit': 'Send for review',
  'register.have_account': 'Already registered? Sign in',
  'register.submitted.heading': 'Sent to Telga for review',
  'register.submitted.reference': 'Your reference number — write it down:',
  'register.submitted.next':
    'A member of Telga staff will check your details and contact you on the number you gave. Keep your original documents ready.',
  'register.submitted.no_account':
    'There is nothing to sign in to yet. Your sign-in details are issued only if your shop is approved.',
  'login.register_cta': 'Register as Telga member',
  // --- Activate this device (D138) ------------------------------------------
  //
  // The code a person carried to the shop, exchanged for the key the machine
  // keeps. CLAUDE.md §18.2. Nothing here may suggest the code itself is what
  // signs the device in afterwards — it is not, and it dies on use.
  'screen.activate': 'Activate this device',
  'activate.heading': 'Activate this machine',
  'activate.intro':
    'Telga gives each machine an activation code, valid for one hour and usable once. Enter it with the device ID Telga gave you.',
  'activate.device': 'Device ID',
  'activate.code': 'Activation code',
  'activate.code.hint': 'Groups of five letters and numbers. Case does not matter.',
  'activate.submit': 'Activate',
  'activate.done.heading': 'This machine is activated',
  'activate.done.key': 'Device key — shown once. Write it down now:',
  'activate.done.warning':
    'Telga keeps only a scrambled copy and can never show this again. If it is lost, ask Telga for a new activation code.',
  'login.activate_cta': 'New machine? Activate it',
  // --- printing (D140) -------------------------------------------------------
  //
  // The notice replaces `voucher.result.no_printer` on the slip screens, which
  // said no printer was configured. That was true and is not any more.
  //
  // It must not promise a printer that is not attached: what Telga does is hand
  // the slip to the device's own print stack, and whether anything comes out is
  // a matter of what that device is paired with.
  'receipt.print': 'Print receipt',
  'receipt.print.notice':
    'Printing uses this device\u2019s own printer. Every slip is marked TRAINING \u2014 NO REAL VALUE.',
  // --- Reporting a problem with a sale (D150) --------------------------------
  //
  // Wording rule: **never promise a refund.** §17 is explicit that an unknown
  // outcome is never auto-refunded, and a form saying "we will return your
  // money" has decided the case before anybody has looked at it. What is
  // promised is an answer.
  'complaint.title':
    'Report a problem',
  'complaint.intro':
    'Tell Telga what went wrong with a sale. Give the transaction number from the receipt and describe the problem in your own words.',
  'complaint.transaction':
    'Transaction number',
  'complaint.transaction.hint':
    'Printed on the receipt. Ask the customer for their copy if you do not have yours.',
  'complaint.description':
    'What went wrong',
  'complaint.submit':
    'Send to Telga',
  'complaint.promise':
    'Telga will check this and give you an answer. If the money is protected while it is checked, Telga will say so — nothing is refunded until the outcome is known.',
  'complaint.sent.heading':
    'Sent to Telga',
  'complaint.sent.reference':
    'Your case number — quote it when you call:',
  'complaint.sent.next':
    'Telga is checking the sale and the provider. You will be told the outcome. Keep serving customers as normal.',
  // --- Asking for a reversal (D151) -------------------------------------------
  //
  // Wording rule, the same as a complaint's: **never promise the money back.**
  // §17.1 makes a merchant's reversal a *request*; a supervisor completes it.
  // A screen that says "your money will be returned" has decided that for them.
  'reverse.title':
    'Ask Telga to reverse a sale',
  'reverse.intro':
    'If a customer handed back a token they could not use, ask Telga to return the money. Telga checks the sale first — the money is not returned until somebody has looked.',
  'reverse.transaction':
    'Transaction number',
  'reverse.reason':
    'Why it should be reversed',
  'reverse.reason.hint':
    'For example: customer returned the token unused.',
  'reverse.submit':
    'Send request',
  'reverse.sent.heading':
    'Request sent to Telga',
  'reverse.sent.reference':
    'Your request number:',
  'reverse.sent.next':
    'Telga will check whether the value reached the customer. Nothing is returned to your balance until that check is done.',
  'reverse.pending.notice':
    'A request for this sale is already with Telga. Do not send another.',
});

export type MessageKey = keyof typeof EN;

export const MESSAGE_KEYS = Object.freeze(Object.keys(EN) as readonly MessageKey[]);

/**
 * Draft Amharic. **REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION.**
 *
 * Partial on purpose — see the file header.
 */
export const AM: Readonly<Partial<Record<MessageKey, string>>> = Object.freeze({
  'sale.action.sell_airtime': 'አየር ሰዓት ሽጥ',
  'sale.amount.select': 'መጠን ይምረጡ',
  'sale.confirm.action': 'ሽያጩን ያረጋግጡ',
  'status.processing': 'በሂደት ላይ',
  'status.pending': 'ግብይቱ በመጠባበቅ ላይ ነው',
  'status.pending.do_not_retry': 'እባክዎ ገና አይድገሙት',
  'status.successful': 'ግብይቱ ተሳክቷል',
  'status.failed': 'ግብይቱ አልተሳካም',
  'status.under_review': 'በምርመራ ላይ',
  'status.provider_unavailable': 'አቅራቢው ለጊዜው አገልግሎት አይሰጥም',
  'status.sales_unavailable': 'ሽያጭ ለጊዜው አይቻልም',
  'status.no_charge': 'ምንም ክፍያ አልተቀነሰም',
  'balance.available': 'ዝግጁ ቀሪ ሂሳብ',
  'balance.reserved': 'የተያዘ ቀሪ ሂሳብ',
  'balance.under_review': 'በምርመራ ላይ ያለ ቀሪ ሂሳብ',
  'commission.net': 'የተጣራ ኮሚሽን',
  'receipt.reprint': 'ደረሰኝ እንደገና ያትሙ',
  'transaction.id': 'የግብይት መለያ ቁጥር',
  'support.contact': 'ድጋፍ ያግኙ',
  'mode.training': 'የልምምድ ሁኔታ — እውነተኛ ዋጋ የለውም',
  'status.pending.message': 'ይህ ግብይት አሁንም እየተጣራ ነው። እባክዎ ገና አይድገሙት።',
  'status.under_review.message':
    'ይህ ግብይት በምርመራ ላይ ነው። ከአቅራቢው ጋር እያጣራን ስንቆይ ቀሪ ሂሳብዎ የተጠበቀ ነው።',
  'status.failed.message': 'ይህ ሽያጭ አልተፈጸመም። ምንም ክፍያ አልተቀነሰም።',
  'status.provider_unavailable.message':
    'ከዚህ አቅራቢ የአየር ሰዓት ለጊዜው አይገኝም። ምንም ክፍያ አልተቀነሰም። ሌሎች አገልግሎቶች እየሠሩ ናቸው።',
  'status.offline.message': 'ሽያጭ ለጊዜው አይቻልም። ታሪክ፣ ሪፖርቶችና ድጋፍ አሁንም ማየት ይችላሉ።',
  'receipt.reprint.notice': 'ይህ እንደገና የታተመ ደረሰኝ ነው። አዲስ ሽያጭ አይደለም።',
  'funding.simulated.notice': 'ይህ የሙከራ የገንዘብ ማስገቢያ ነው። እውነተኛ ገንዘብ አልተካተተም።',
  'error.validation.recipient': 'የስልክ ቁጥሩን አረጋግጠው እንደገና ይሞክሩ።',
  'error.balance.insufficient': 'ለዚህ ሽያጭ በቂ ዝግጁ ቀሪ ሂሳብ የለም።',
  'error.permission.denied': 'የእርስዎ ሚና ይህን ተግባር አይፈቅድም።',
  'error.session.expired': 'ክፍለ ጊዜዎ አብቅቷል። እንደገና ይግቡ። ምንም አልጠፋም።',
  'error.printer.failed': 'ደረሰኙ አልታተመም። ሽያጩ ተጠናቋል — እንደገና ማተም ይችላሉ።',
  'error.duplicate.blocked': 'ይህ ሽያጭ አስቀድሞ በሂደት ላይ ነው። እንደገና አይጀምሩት።',
  'error.network_unavailable':
    'ቴልጋ ላይ መድረስ አልተቻለም። የዚህ ሽያጭ ውጤት እስካሁን አይታወቅም — እንደገና አይሞክሩ።',
  'voucher.action.print': 'አትም',
  'voucher.action.cancel': 'ሰርዝ',
  'voucher.action.back': 'ተመለስ',
  'voucher.action.continue': 'ቀጥል',
  'voucher.product.airtime': 'አየር ሰዓት',
  'voucher.data.unavailable': 'በልምምድ ውስጥ አይገኝም',
  'voucher.pin.prompt': 'የልምምድ ቫውቸር ለመግዛት ፒን ያስገቡ',
  'voucher.pin.clear': 'አጽዳ',
  'voucher.pin.confirm': 'እሺ / አረጋግጥ',
  'voucher.result.no_printer': 'የልምምድ ቫውቸር በስክሪኑ ላይ ታይቷል — አታሚ አልተዘጋጀም።',
  'voucher.result.preview_notice':
    'ቅድመ እይታ ብቻ። የፒን ማረጋገጫና የቫውቸር መፍጠር እስካሁን አልነቃም — ምንም የልምምድ ቫውቸር አልተመዘገበም።',
  'voucher.result.new_sale': 'አዲስ ሽያጭ',
  'voucher.amount.invalid': 'ለዚህ አውታረ መረብ ትክክለኛ መጠን ይምረጡ።',
  'sale.amount.select_placeholder': 'የአየር ሰዓት መጠን ይምረጡ',
  'sale.amount.custom': 'ሌላ መጠን',
  'sale.amount.custom_label': 'መጠን በብር',
  'sale.amount.custom.below_min': 'ይህ መጠን ከልምምድ ዝቅተኛ በታች ነው።',
  'sale.amount.custom.above_max': 'ይህ መጠን ከልምምድ ከፍተኛ በላይ ነው።',
  'sale.amount.custom.not_multiple': 'ሙሉ የብር ቁጥር ያስገቡ።',
  'sale.amount.custom.not_a_number': 'ትክክለኛ መጠን ያስገቡ።',
  'voucher.pin.heading': 'የግብይት ፒን ያረጋግጡ',
  'voucher.product.topup': 'ቀጥታ ሙሌት',
  'voucher.summary.merchant': 'የልምምድ ነጋዴ',
  'voucher.summary.amount': 'መጠን',
  'voucher.summary.total': 'ጠቅላላ',
  'voucher.summary.profit': 'የእርስዎ ትርፍ',
  'voucher.summary.recipient': 'ስልክ ቁጥር',
  'topup.tile.label': 'ስልክ ሙላ',
  'topup.phone.label': 'የደንበኛ ስልክ ቁጥር',
  'topup.phone.hint': 'አየር ሰዓቱ የሚላክበት ቁጥር።',
  'topup.phone.invalid': 'ትክክለኛ ስልክ ቁጥር ያስገቡ።',
  'topup.phone.required': 'ለቀጥታ ሙሌት ስልክ ቁጥር ያስፈልጋል።',
  'nav.main': 'ዋና',
  'menu.lock': 'ቁልፍ',
  'card.read': 'ካርድ አንብብ',
  'card.declined_heading': 'አልጸደቀም',
  'card.no_response_heading': 'ከባንኩ ምላሽ የለም',
  'card.try_again': 'ደንበኛው በተመሳሳይ ካርድ እንደገና ይሞክር።',
  'card.number': 'ካርድ',
  'card.scheme': 'ዓይነት',
  'card.entry_mode': 'የተነበበበት',
  'card.simulator_title': 'የሥልጠና ካርድ — እውነተኛ አንባቢ ይህንን ራሱ ያቀርባል',
  'settings.shift.hint': 'ፈረቃ ኦፕሬተሩ የጀመረበትንና የጨረሰበትን ጊዜ ይመዘግባል። የራሱ ገንዘብ የለውም።',
  'settings.shift.statement': 'የዚህ ፈረቃ መግለጫ',
  'settings.account.operator': 'ኦፕሬተር',
  'settings.account.device': 'መሣሪያ',
  'settings.account.merchant': 'ነጋዴ',
  'settings.account.hint':
    'ተልጋ በኦፕሬተር መለያ፣ በፒን እና በመሣሪያ ቁልፍ ይገባል — የይለፍ ቃል የለም። ከታች ያለውን ፒን ቀይር ይጠቀሙ።',
  'outage.heading': 'አገልግሎቱ አይገኝም',
  'outage.unavailable': 'አሁን አይገኝም',
  'outage.no_charge': 'ምንም አልተከፈለም። ሽያጭ አልተደረገም፤ ኮሚሽንም አልተገኘም።',
  'outage.last_checked': 'የመጨረሻ ማረጋገጫ',
  'outage.still_available': 'አሁንም የሚገኙ',
  'offline.heading': 'ተልጋ አይገኝም',
  'offline.no_sales': 'ግንኙነቱ እስኪመለስ ድረስ አዲስ ሽያጭ ማድረግ አይቻልም።',
  'offline.no_offline_vending': 'ከመስመር ውጭ መሸጥ አይፈቀድም። ይህ መሣሪያ ሊጨርሰው ለማይችል ሽያጭ ገንዘብ አይቀበሉ።',
  'offline.last_seen': 'የመጨረሻ ግንኙነት',
  'offline.still_available': 'አሁንም የሚሠሩ',
  'receipt.lookup_title': 'የሱቅ ቅጂ — ፍለጋ',
  'receipt.lookup_note': 'ሽያጩን እንደገና ለማግኘት ይህንን ያስቀምጡ።',
  'dashboard.low_balance': 'የመሸጫ ቀሪ ሂሳብዎ እያለቀ ነው። ከማለቁ በፊት ይሙሉ።',
  'statements.admin_only': 'መግለጫዎች ለባለቤት ብቻ ተዘጋጅተዋል። የሱቁን ባለቤት ይጠይቁ።',
  'card.decline.insufficient_funds': 'በካርዱ ላይ በቂ ገንዘብ የለም። ምንም አልተከፈለም።',
  'card.decline.wrong_pin': 'የካርድ ፒን ትክክል አይደለም። ደንበኛው እንደገና ይሞክር።',
  'card.decline.expired': 'የካርዱ ጊዜ አልፎበታል። ምንም አልተከፈለም።',
  'card.decline.blocked': 'ካርዱ ታግዷል። ምንም አልተከፈለም።',
  'card.decline.limit': 'መጠኑ ከካርዱ ገደብ በላይ ነው። ምንም አልተከፈለም።',
  'card.decline.issuer': 'ባንኩ አልመለሰም። ከጥቂት ጊዜ በኋላ ይሞክሩ።',
  'card.decline.generic': 'ካርዱ ተቀባይነት አላገኘም። ምንም አልተከፈለም።',
  'card.no_response': 'ባንኩ አልመለሰም። እንደገና አይሞክሩ፤ ዕቃም አይስጡ — በመጀመሪያ ግብይቱን ያረጋግጡ።',
  'card.not_read': 'ካርዱ አልተነበበም። ደንበኛው እንደገና ያቅርብ።',
  'card.no_reader': 'በዚህ መሣሪያ ላይ የካርድ አንባቢ አልተገናኘም።',
  'card.present': 'ካርዱን ይንኩ፣ ያስገቡ ወይም ያንሸራትቱ',
  'card.approved': 'ጸድቋል',
  'card.reference': 'የፈቃድ ቁጥር',
  'menu.manage': 'አስተዳደር',
  'lock.heading': 'ማያ ገጹ ተቆልፏል',
  'lock.pin_label': 'ለመክፈት ፒንዎን ያስገቡ',
  'lock.unlock': 'ክፈት',
  'lock.wrong': 'ያስገቡት ፒን ትክክል አይደለም። ማያ ገጹ ተቆልፎ ይቆያል።',
  'menu.open': 'ምናሌ ክፈት',
  'menu.statements': 'መግለጫዎች',
  'menu.end_shift': 'ፈረቃ ጨርስ',
  'menu.customers': 'የደንበኞች ዝርዝር',
  'menu.learning': 'ትምህርት',
  'menu.settings': 'ቅንብሮች',
  'menu.help': 'እገዛ',
  'menu.logout': 'ውጣ',
  'screen.help': 'የተልጋ ድጋፍ',
  'screen.learning': 'ተልጋን እንዴት እንደሚጠቀሙ',
  'screen.customers': 'የደንበኞች ዝርዝር',
  'screen.end_shift': 'ፈረቃ ጨርስ',
  'help.intro': 'ይህ መሣሪያ መመለስ ለማይችለው ማንኛውም ነገር የተልጋ ድጋፍ።',
  'help.phone': 'ስልክ',
  'help.email': 'ኢሜይል',
  'help.hours': 'የሥራ ሰዓት',
  'help.address': 'አድራሻ',
  'help.reference_hint': 'ከደረሰኙ ላይ ያለውን የግብይት ማጣቀሻ ያዘጋጁ — ሽያጭን ለማግኘት ፈጣኑ መንገድ ነው።',
  'learning.intro': 'ከታች ያለው እያንዳንዱ ደረጃ በዚህ መሣሪያ ላይ የሚሞክሩት አንድ ነገር ነው። በቅደም ተከተል ይሂዱ።',
  'customers.empty': 'እስካሁን የተቀመጠ ደንበኛ የለም።',
  'customers.name': 'የደንበኛ ስም',
  'customers.phone': 'ስልክ ቁጥር',
  'customers.add': 'ደንበኛ አስቀምጥ',
  'customers.privacy': 'የተቀመጡ ቁጥሮች ደረሰኝ እንደሚያትማቸው ተሸፍነው ይቀመጣሉ።',
  'customers.invalid': 'ስም እና ትክክለኛ ስልክ ቁጥር ያስገቡ።',
  'shift.open_since': 'ፈረቃ የተከፈተው ከ',
  'shift.none_open': 'የተከፈተ ፈረቃ የለም።',
  'shift.end': 'ፈረቃ ጨርስ',
  'shift.end_confirm': 'ይህን ፈረቃ ይጨርሱ?',
  'shift.ended': 'ፈረቃ ተጠናቋል።',
  'settings.section.shift': 'የፈረቃ ቅንብሮች',
  'settings.section.account': 'የመለያ ቅንብሮች',
  'settings.section.app': 'የመተግበሪያ ቅንብሮች',
  'settings.section.admin': 'ለአስተዳዳሪ ብቻ',
  'settings.section.security': 'ደህንነት',
  'settings.section.about': 'ስለ እና ፖሊሲዎች',
  'settings.toggle.sound': 'ድምጽ አጫውት',
  'settings.toggle.hide_balance': 'የተልጋ ቀሪ ሂሳብ ደብቅ',
  'settings.toggle.low_balance': 'ቀሪ ሂሳብ ሲያንስ አሳውቀኝ',
  'settings.toggle.statements_admin': 'መግለጫዎች በአስተዳዳሪ ብቻ ይታዩ',
  'settings.toggle.print_barcode': 'በደረሰኝ ላይ ባርኮድ አትም',
  'settings.toggle.print_lookup': 'የፍለጋ ደረሰኝ አትም',
  'settings.toggle.pin_lock': 'ለመክፈት ፒን ይጠየቅ',
  'settings.lock_seconds': 'ማያ ገጹ የሚቆለፍበት ጊዜ (ሰከንድ)',
  'settings.account.phone': 'ስልክ ቁጥር ቀይር',
  'settings.account.password': 'የይለፍ ቃል ቀይር',
  'settings.account.details': 'መረጃዎን ይቀይሩ',
  'settings.about.telga': 'ስለ ተልጋ',
  'settings.about.terms': 'ውሎች እና ሁኔታዎች',
  'settings.about.privacy': 'የግላዊነት ፖሊሲ',
  'settings.about.cookies': 'የኩኪ ፖሊሲ',
  'settings.back': 'ተመለስ',
  'balance.top_up': 'ቀሪ ሂሳብዎን ይሙሉ',
  'balance.top_up.open': 'ወደ ቀሪ ሂሳብ ጨምር',
  'balance.top_up.bank': 'የባንክ ተቀማጭ',
  'balance.top_up.pay': 'የተልጋ ፔይ ቀሪ ሂሳብ',
  'balance.top_up.profit': 'ትርፍ',
  'screen.launcher': 'ተልጋ',
  'screen.pay_settings': 'የቴልጋ ፔይ ቅንብሮች',
  'statements.title': 'መግለጫ',
  'statements.from': 'ከ',
  'statements.to': 'እስከ',
  'statements.apply': 'ተግብር',
  'statements.clear': 'አጽዳ',
  'statements.sales': 'ሽያጮች',
  'statements.gross': 'የተሸጠ',
  'statements.profit': 'ትርፍ',
  'statements.reversals': 'የተመለሱ',
  'statements.total': 'ጠቅላላ',
  'statements.note': 'ትርፍ በእያንዳንዱ ቀን የተገኘው ነው። ትርፍን ወደ መሸጫ ቀሪ ሂሳብ ማዘዋወር ሽያጭ አይደለም፤ የተመለሰ ሽያጭ ግን ይቀነሳል።',
  'pay.records.transactions_title': 'የቴልጋ ፔይ ግብይቶች',
  'pay.records.statements_title': 'የቴልጋ ፔይ መግለጫዎች',
  'pay.records.cards_not_stored': 'የካርድ ሙከራዎች አይመዘገቡም። የተመሰለ ካርድ ዋጋ ስለማያንቀሳቅስ በመዝገቡ ላይ ምንም አይጻፍም። የልምምድ ተቀማጮች ግን ይመዘገባሉ።',
  'pay.records.empty': 'እስካሁን የተመዘገበ የለም።',
  'pay.records.count': 'ብዛት',
  'pay.settings.flag_card_note': 'የካርድ አስመሳይ። ከኋላው ወደ ባንክ የሚደርስ የለም።',
  'pay.settings.flag_accept_note': 'እውነተኛ የካርድ ክፍያ መቀበል። አግኚና ፈቃድ ይፈልጋል።',
  'pay.settings.flag_deposit_note': 'ወደ የልምምድ ቀሪ ሂሳብ የተመሰለ ተቀማጭ።',
  'pay.settings.flag_cash_note': 'ጥሬ ገንዘብ መቀበል ወይም መክፈል። ሕጋዊ ግምገማ ያስፈልጋል።',
  'pay.settings.intro': 'እነዚህ ቅንብሮች የቴልጋ ፔይ ናቸው። የሱቁ ደረሰኝና የንግድ ዝርዝሮች ከቴልጋ ሽያጭ ጋር የተጋሩ ናቸው።',
  'pay.settings.records': 'መዝገቦች',
  'pay.settings.transactions': 'የካርድ ግብይቶች',
  'pay.settings.statements': 'የካርድ መግለጫዎች',
  'pay.settings.cards': 'የልምምድ ካርዶች',
  'pay.settings.cards_hint': 'ማመሳከሪያ ነው፤ ቅንብር አይደለም። እነዚህ ካርዶች በአስመሳዩ ውስጥ ቋሚ ናቸው።',
  'pay.settings.flags': 'የበራው',
  'pay.settings.flag_on': 'በርቷል',
  'pay.settings.flag_off': 'ጠፍቷል',
  'pay.settings.slips': 'ደረሰኞች',
  'pay.settings.slips_note': 'የደረሰኝ ስፋትና የንግድ ዝርዝሮች በሁሉም የቴልጋ ደረሰኞች ላይ ይታተማሉ። በቴልጋ ሽያጭ ቅንብሮች ውስጥ ይዘጋጃሉ።',
  'pay.settings.account': 'የገባው',
  'pay.settings.operator': 'ኦፕሬተር',
  'pay.settings.device': 'መሣሪያ',
  'pay.settings.merchant': 'ነጋዴ',
  'settings.slip_size': 'የደረሰኝ ስፋት',
  'screen.launcher_apps': 'የተልጋ አገልግሎት ይምረጡ',
  'screen.profit_transfer': 'ትርፍን ወደ መሸጫ ቀሪ ሂሳብ ያዛውሩ',
  'profit.transfer.action': 'ወደ መሸጫ ቀሪ ሂሳብ ያዛውሩ',
  'profit.transfer.available': 'ሊዛወር የሚችል ትርፍ',
  'profit.transfer.amount_label': 'መጠን በብር',
  'profit.transfer.amount_invalid': 'ቢያንስ 1፣ ሙሉ ቁጥር ብር ያስገቡ።',
  'profit.transfer.exceeds': 'ካለዎት ትርፍ ይበልጣል። ምንም አልተዛወረም።',
  'profit.transfer.confirm': 'እሺ',
  'profit.transfer.done': 'ወደ መሸጫ ቀሪ ሂሳብዎ ተዛውሯል።',
  'profit.transfer.remaining': 'የቀረው ትርፍ',
  'profit.transfer.new_balance': 'አዲስ የመሸጫ ቀሪ ሂሳብ',
  'profit.transfer.none': 'እስካሁን የሚዛወር ትርፍ የለም።',
  'settings.pin.heading': 'የግብይት ፒን ይቀይሩ',
  'settings.pin.current': 'የአሁኑ ፒን',
  'settings.pin.new': 'አዲስ ፒን',
  'settings.pin.confirm': 'አዲሱን ፒን ያረጋግጡ',
  'settings.pin.save': 'ፒን ቀይር',
  'settings.pin.changed': 'የግብይት ፒን ተቀይሯል። ከአሁን በኋላ አዲሱን ፒን ይጠቀሙ።',
  'settings.pin.wrong_current': 'ያስገቡት የአሁኑ ፒን ትክክል አይደለም። ምንም አልተቀየረም።',
  'settings.pin.weak': 'ሌላ ባለ ስድስት አኃዝ ፒን ይምረጡ። 111111 ወይም 123456 ያስወግዱ።',
  'settings.pin.mismatch': 'ሁለቱ አዲስ ፒኖች አይመሳሰሉም። ምንም አልተቀየረም።',
  'settings.business.heading': 'የንግድ መረጃ',
  'settings.business.hint': 'በእያንዳንዱ ደረሰኝ ላይ ይታተማል። ተልጋ እነዚህን አያረጋግጥም።',
  'settings.business.name': 'የንግድ ስም',
  'settings.business.address': 'አድራሻ',
  'settings.business.phone': 'የሱቅ ስልክ ቁጥር',
  'settings.business.tin': 'የግብር መለያ ቁጥር',
  'settings.business.licence': 'የንግድ ፈቃድ ቁጥር',
  'settings.business.footer': 'በደረሰኙ ላይ የመዝጊያ መስመር',
  'launcher.open_telga': 'ቴልጋን ለመክፈት ይንኹ',
  'voucher.quantity.label': 'ስንት ቫውቸሮች',
  'voucher.quantity.invalid': 'ከ1 እስከ 20 ቫውቸሮች ይምረጡ።',
  'voucher.quantity.decrease': 'አንድ ይቀንሱ',
  'voucher.quantity.increase': 'አንድ ይጨምሩ',
  'voucher.summary.quantity': 'ቫውቸሮች',
  'voucher.summary.each': 'የአንዱ ዋጋ',
  'receipt.slip.batch_position': 'ቫውቸር',
  'voucher.action.main': 'ዋና',
  'voucher.action.main_confirm': 'ይህን ሽያጭ ትተው ወደ ዋናው ማያ ገጽ ይሂዱ? ምንም ቫውቸር አይሰጥም።',
  'voucher.product.data': 'ዳታ',
  'data.category.select': 'የዳታ ዓይነት ይምረጡ',
  'data.package.select': 'ጥቅል ይምረጡ',
  'data.column.volume': 'ጥቅል',
  'data.column.validity': 'የሚያገለግልበት ጊዜ',
  'data.phone.label': 'የደንበኛ ስልክ ቁጥር',
  'data.phone.required': 'ለዳታ ጥቅል ስልክ ቁጥር ያስፈልጋል።',
  'data.category.monthly': 'ወርሃዊ',
  'data.category.weekly': 'ሳምንታዊ',
  'data.category.daily': 'ዕለታዊ',
  'data.category.hourly': 'በሰዓት',
  'data.category.weekend': 'የሳምንት መጨረሻ',
  'data.category.all_access': 'ሙሉ መዳረሻ',
  'data.category.lte': 'ኤልቲኢ',
  'data.category.social': 'ማህበራዊ',
  'data.category.voice': 'ድምጽ',
  'receipt.slip.network_code': 'ኔትወርክ',
  'receipt.slip.voucher_pin': 'የቫውቸር ፒን',
  'receipt.slip.token_reference': 'የቶክን ማጣቀሻ',
  'receipt.slip.dial_string': 'ለመሙላት ይደውሉ',
  'receipt.slip.simulated_code_notice': 'የተመሰለ ኮድ — አየር ሰዓት አይሞላም',
  'voucher.error.insufficient_balance': 'በቂ የልምምድ ቀሪ ሂሳብ የለም። ምንም ቫውቸር አልተሰጠም።',
  'voucher.error.order_expired': 'ይህ ትዕዛዝ ከመረጋገጡ በፊት ጊዜው አልፎበታል። ምንም ቫውቸር አልተሰጠም።',
  'voucher.error.order_not_open': 'ይህ ትዕዛዝ አስቀድሞ ተጠናቅቋል ወይም ተሰርዟል። ምንም ቫውቸር አልተሰጠም።',
  'voucher.error.duplicate': 'ይህ ቫውቸር አስቀድሞ ተሰጥቷል። እንደገና አልተሰጠም።',
  'voucher.error.generic': 'ቫውቸሩን ማጠናቀቅ አልተቻለም። ምንም ቫውቸር አልተሰጠም።',
  'voucher.result.failed_title': 'ቫውቸር አልተሰጠም',
  'voucher.action.back_to_vouchers': 'ወደ ቫውቸሮች ተመለስ',
  'voucher.action.home': 'መነሻ',
  'receipt.not_available': 'ለዚህ ግብይት እስካሁን ደረሰኝ አይገኝም።',
  'receipt.slip.title': 'የግብይት ደረሰኝ',
  'receipt.slip.reprint_notice': 'እንደገና የታተመ — አዲስ ሽያጭ አይደለም',
  'receipt.action.close': 'ዝጋ',
  'receipt.action.print': 'አትም',
  'receipt.print.failed': 'ማተም አልተጠናቀቀም። ግብይቱ አልተለወጠም።',
  'transactions.empty': 'እስካሁን ምንም ግብይት የለም።',
  'transactions.column.datetime': 'ቀን እና ሰዓት',
  'transactions.column.service': 'አገልግሎት',
  'transactions.column.amount': 'መጠን',
  'transactions.column.status': 'ሁኔታ',
  'transactions.column.reference': 'ማጣቀሻ',
  'voucher.pin.wrong': 'የተሳሳተ የግብይት ፒን። ምንም ቫውቸር አልተሰጠም።',
  'voucher.pin.locked': 'በጣም ብዙ የተሳሳቱ የፒን ሙከራዎች። የቫውቸር ማረጋገጫ ለጥቂት ደቂቃዎች ተቆልፏል። መግቢያዎ አልተነካም።',
  'launcher.tile.telga.label': 'ቴልጋ',
  'launcher.tile.telga.subtitle': 'ሽያጭና የነጋዴ አገልግሎቶች',
  'launcher.tile.telgapay.label': 'ቴልጋ ፔይ',
  'launcher.tile.telgapay.subtitle': 'የልምምድ የካርድ ክፍያ አስመሳይ',
  'dashboard.balance.pill': 'ቀሪ ሂሳብ',
  'dashboard.profit.pill': 'ትርፍ',
  'dashboard.profit.unavailable': 'እስካሁን አይገኝም',
  'dashboard.service.data': 'ዳታ',
  'dashboard.service.electricity': 'ኤሌክትሪክ',
  'dashboard.service.account': 'መለያ',
  'dashboard.service.water': 'ውሃ',
  'dashboard.service.dstv': 'ዲኤስቲቪ',
  'dashboard.service.telecom': 'የቴሌኮም ክፍያ',
  'dashboard.service.traffic': 'ትራፊክ',
  'dashboard.service.lottery': 'ሎተሪ',
  'dashboard.service.tickets': 'ትኬቶች',
  'dashboard.service.fuel': 'ነዳጅ',
  'dashboard.service.internet': 'ኢንተርኔት',
  'dashboard.service.school': 'የትምህርት ክፍያ',
  'dashboard.service.insurance': 'መድን',
  'dashboard.service.govfees': 'የመንግሥት ክፍያዎች',
  'dashboard.nav.reprint': 'እንደገና አትም',
  'dashboard.coming_soon.message': 'በቅርቡ ይመጣል — ይህ አገልግሎት በልምምድ ውስጥ አልነቃም።',
  'dashboard.nav.prepaid': 'ቅድመ ክፍያ',
  'dashboard.nav.payments': 'ክፍያዎች',
  'dashboard.back_to_launcher': 'የቴልጋ ማስጀመሪያ',
  'pay.banner': 'የልምምድ የካርድ ክፍያ አስመሳይ — እውነተኛ አስተናጋጅ አልተገናኘም።',
  'pay.no_transactions': 'በልምምድ ውስጥ ምንም የቴልጋ ፔይ ግብይት አልተመዘገበም።',
  'pay.todays_sales_label': 'የዛሬው የቴልጋ ሽያጭ',
  'pay.transactions_label': 'ግብይት(ቶች)',
  'pay.purchase.label': 'ግዢ',
  'pay.cashback.label': 'ካሽባክ',
  'pay.amount.label': 'መጠን',
  'pay.note.label': 'ማስታወሻ ጨምር',
  'pay.pay_now': 'አሁን ክፈል',
  'pay.card.prompt': 'እባክዎ ካርድ ያስገቡ፣ ያንሸራትቱ ወይም ይንኩ',
  'pay.card.tap': 'ንካ / ንክኪ የሌለው',
  'pay.card.insert': 'አስገባ / ቺፕ',
  'pay.card.swipe': 'ማንሸራተት',
  'pay.card.example_notice': 'ቪዛ እና ማስተርካርድ የልምምድ ምሳሌዎች ብቻ ናቸው። ምንም እውነተኛ የካርድ አውታረ መረብ አልተገናኘም።',
  'pay.outcome.approved': 'የልምምድ አስመሳይ ብቻ — ምንም እውነተኛ ክፍያ አልተከናወነም።',
  'pay.outcome.declined': 'ተቀባይነት አላገኘም — በቂ የልምምድ ገንዘብ የለም። ምንም ክፍያ አልተፈጸመም።',
  'pay.outcome.read_error': 'ካርዱ ሊነበብ አልቻለም። እንደገና ይሞክሩ ወይም ሌላ ዘዴ ይምረጡ።',
  'pay.outcome.cancelled': 'ተሰርዟል። ምንም ክፍያ አልተፈጸመም።',
  'pay.card.practice_heading': 'የተለየ የልምምድ ውጤት ይለማመዱ',
  'pay.card.practice_declined': 'ተቀባይነት አላገኘም',
  'pay.card.practice_read_error': 'ካርድ ንባብ ስህተት',
  'pay.card.practice_cancelled': 'ተሰርዟል',
  'pay.retry': 'እንደገና ይሞክሩ',
  'pay.deposit.label': 'ቀሪ ሂሳብ ጨምር',
  'pay.deposit.heading': 'የልምምድ ቀሪ ሂሳብ ጨምር',
  'pay.deposit.prompt': 'ምን ያህል የልምምድ ቀሪ ሂሳብ መጨመር ይፈልጋሉ?',
  'pay.deposit.confirm': 'ወደ ቀሪ ሂሳብ ጨምር',
  'pay.deposit.notice':
    'ለልምምድ ብቻ። ይህ የአየር ሰዓት ሽያጭ ለመለማመድ የተመሰለ ቀሪ ሂሳብ ይጨምራል። እውነተኛ ካርድ አይነበብም እና እውነተኛ ገንዘብ አይንቀሳቀስም።',
  'pay.deposit.credited': 'የተመሰለ ቀሪ ሂሳብ ተጨምሯል።',
  'pay.deposit.invalid': 'ለመጨመር ትክክለኛ መጠን ያስገቡ።',
  'pay.deposit.slip_title': 'የቴልጋ ፔይ ተቀማጭ ደረሰኝ',
  'pay.deposit.method': 'የካርድ ዘዴ',
  'settings.tile.label': 'ቅንብሮች',
  'settings.heading': 'የደረሰኝ እና የልምምድ ቅንብሮች',
  'settings.slip_size.label': 'የደረሰኝ ስፋት',
  'settings.slip_size.58': '58 ሚሜ (ጠባብ ጥቅል)',
  'settings.slip_size.80': '80 ሚሜ (ሰፊ ጥቅል)',
  'settings.advert.label': 'በደረሰኙ ላይ የሚታተም የማስታወቂያ መስመር',
  'settings.advert.hint': 'በእያንዳንዱ ደረሰኝ ግርጌ ይታተማል። ምንም ካልፈለጉ ባዶ ይተዉት።',
  'settings.profit.label': 'የልምምድ ትርፍ መቶኛ',
  'settings.profit.hint':
    'የልምምድ አኃዝ ብቻ። የተደራደረ ኮሚሽን አይደለም እና የምርት ተመን አይደለም።',
  'settings.profit.invalid': 'ከ0 እስከ 100 ያለ መቶኛ ያስገቡ።',
  'settings.save': 'ቅንብሮችን አስቀምጥ',
  'settings.saved': 'ቅንብሮች ተቀምጠዋል።',
  'settings.permission_denied': 'እነዚህን ቅንብሮች መቀየር የሚችለው የሱቁ ባለቤት ብቻ ነው።',
  'settings.signout': 'ሙሉ በሙሉ ውጣ',
  'settings.signout.confirm':
    'ሙሉ በሙሉ ይውጡ? ይህ መሣሪያ ሁሉንም የመግቢያ መረጃዎችዎን እንደገና ይጠይቃል።',
  'settings.signout.hint':
    'እዚህ መውጣት መሣሪያውን፣ የመሣሪያ ቁልፉንና ኦፕሬተሩን ያጸዳል። የእንቅስቃሴ-አልባ ጊዜ ማብቃት ፒኑን ብቻ ይጠይቃል።',
  'receipt.training_notice': 'ልምምድ — እውነተኛ ዋጋ የለውም',

  // --- Register as Telga member (D138) --------------------------------------------
  // DRAFT, like every Amharic value in this file. REQUIRES NATIVE AMHARIC
  // REVIEW BEFORE PRODUCTION. The wording rule above applies here too: none of
  // these may read as "your account has been created".
  'screen.register': 'እንደ ተልጋ አባል ይመዝገቡ',
  'register.heading': 'ሱቅዎን በተልጋ ያስመዝግቡ',
  'register.intro':
    'ይህንን ይሙሉ፤ ተልጋ ይመረምረዋል። ፈቃድ በራሱ አይሰጥም፤ እስካሁን ምንም መለያ አልተፈጠረም። ሱቅዎ ከተፈቀደ ተልጋ የመግቢያ መረጃዎን ይልክልዎታል።',
  'register.legal_name': 'የንግድ ስም',
  'register.legal_name.hint': 'በንግድ ፈቃድዎ ላይ እንደተጻፈው በትክክል።',
  'register.owner_name': 'የባለቤቱ ሙሉ ስም',
  'register.phone': 'የስልክ ቁጥር',
  'register.phone.hint': 'ተልጋ ስለ ማመልከቻዎ በዚህ ቁጥር ይደውላል።',
  'register.email': 'ኢሜይል (አማራጭ)',
  'register.email.hint': 'ኢሜይል ካልተጠቀሙ ባዶ ይተዉት።',
  'register.address': 'የሱቅ አድራሻ',
  'register.locality': 'ከተማ ወይም ክፍለ ከተማ',
  'register.documents': 'ሰነዶችዎ',
  'register.documents.hint':
    'በእያንዳንዱ ሰነድ ላይ የተጻፈውን ቁጥር ያስገቡ። እዚህ ፎቶ አይላኩ — ተልጋ ዋናዎቹን ሰነዶች ከእርስዎ ጋር ያረጋግጣል።',
  'register.trade_licence': 'የንግድ ፈቃድ ቁጥር',
  'register.trade_licence_expiry': 'የንግድ ፈቃድ የሚያበቃበት ቀን',
  'register.tin': 'የግብር መለያ ቁጥር (TIN)',
  'register.photo_id': 'የባለቤቱ መታወቂያ ቁጥር',
  'register.photo_id.hint': 'ብሔራዊ መታወቂያ፣ ፓስፖርት ወይም የመንጃ ፈቃድ።',
  'register.submit': 'ለምርመራ ላክ',
  'register.have_account': 'ቀድሞ ተመዝግበዋል? ይግቡ',
  'register.submitted.heading': 'ለተልጋ ምርመራ ተልኳል',
  'register.submitted.reference': 'የማጣቀሻ ቁጥርዎ — ይመዝግቡት፦',
  'register.submitted.next':
    'የተልጋ ሠራተኛ መረጃዎን አረጋግጦ በሰጡት ቁጥር ይደውልልዎታል። ዋና ሰነዶችዎን ዝግጁ ያድርጉ።',
  'register.submitted.no_account':
    'እስካሁን የሚገቡበት መለያ የለም። የመግቢያ መረጃዎ የሚሰጠው ሱቅዎ ሲፈቀድ ብቻ ነው።',
  'login.register_cta': 'እንደ ተልጋ አባል ይመዝገቡ',
  // --- Activate this device (D138) ------------------------------------------
  // DRAFT. REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION.
  'screen.activate': 'ይህን መሣሪያ ያግብሩ',
  'activate.heading': 'ይህን መሣሪያ ያግብሩ',
  'activate.intro':
    'ተልጋ ለእያንዳንዱ መሣሪያ የማግበሪያ ኮድ ይሰጣል፤ ለአንድ ሰዓት ብቻ የሚሠራ እና አንድ ጊዜ የሚያገለግል። ተልጋ ከሰጠዎት የመሣሪያ መለያ ጋር ያስገቡት።',
  'activate.device': 'የመሣሪያ መለያ',
  'activate.code': 'የማግበሪያ ኮድ',
  'activate.code.hint': 'በአምስት ፊደላትና ቁጥሮች ተከፍሎ። ትልቅ ወይም ትንሽ ፊደል ችግር የለውም።',
  'activate.submit': 'አግብር',
  'activate.done.heading': 'ይህ መሣሪያ ተግብሯል',
  'activate.done.key': 'የመሣሪያ ቁልፍ — አንድ ጊዜ ብቻ ይታያል። አሁን ይመዝግቡት፦',
  'activate.done.warning':
    'ተልጋ የተመሰጠረ ቅጂ ብቻ ነው የሚይዘው፤ ዳግም ሊያሳይዎት አይችልም። ከጠፋ ከተልጋ አዲስ የማግበሪያ ኮድ ይጠይቁ።',
  'login.activate_cta': 'አዲስ መሣሪያ? ያግብሩት',
  // --- printing (D140) -------------------------------------------------------
  // DRAFT. REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION.
  'receipt.print': 'ደረሰኝ አትም',
  'receipt.print.notice':
    'ማተሚያው የዚህ መሣሪያ ነው። እያንዳንዱ ደረሰኝ «TRAINING — NO REAL VALUE» የሚል ምልክት አለው።',
  // --- Reporting a problem with a sale (D150) --------------------------------
  // DRAFT. REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION.
  'complaint.title':
    'ችግር ያሳውቁ',
  'complaint.intro':
    'በሽያጭ ላይ ምን እንደተፈጠረ ለተልጋ ይንገሩ። ከደረሰኙ ላይ የግብይት ቁጥሩን ያስገቡና ችግሩን በራስዎ ቃል ይግለጹ።',
  'complaint.transaction':
    'የግብይት ቁጥር',
  'complaint.transaction.hint':
    'በደረሰኙ ላይ ተጽፏል። የእርስዎ ከሌለ የደንበኛውን ቅጂ ይጠይቁ።',
  'complaint.description':
    'ምን ተፈጠረ',
  'complaint.submit':
    'ወደ ተልጋ ላክ',
  'complaint.promise':
    'ተልጋ ይህንን አረጋግጦ መልስ ይሰጥዎታል። በሚጣራበት ጊዜ ገንዘቡ የተጠበቀ ከሆነ ተልጋ ይነግርዎታል — ውጤቱ እስኪታወቅ ድረስ ምንም አይመለስም።',
  'complaint.sent.heading':
    'ወደ ተልጋ ተልኳል',
  'complaint.sent.reference':
    'የጉዳይዎ ቁጥር — ሲደውሉ ይጥቀሱት፦',
  'complaint.sent.next':
    'ተልጋ ሽያጩንና አቅራቢውን እያጣራ ነው። ውጤቱ ይነገርዎታል። እንደተለመደው ደንበኞችን ማገልገልዎን ይቀጥሉ።',
  // --- Asking for a reversal (D151) -------------------------------------------
  // DRAFT. REQUIRES NATIVE AMHARIC REVIEW BEFORE PRODUCTION.
  'reverse.title':
    'ተልጋ ሽያጭ እንዲመልስ ይጠይቁ',
  'reverse.intro':
    'ደንበኛ መጠቀም ያልቻለውን ቶከን ከመለሰ፣ ተልጋ ገንዘቡን እንዲመልስ ይጠይቁ። ተልጋ መጀመሪያ ሽያጩን ያረጋግጣል — ሰው እስኪያየው ድረስ ገንዘቡ አይመለስም።',
  'reverse.transaction':
    'የግብይት ቁጥር',
  'reverse.reason':
    'ለምን መመለስ እንዳለበት',
  'reverse.reason.hint':
    'ለምሳሌ፦ ደንበኛው ቶከኑን ሳይጠቀም መልሷል።',
  'reverse.submit':
    'ጥያቄ ላክ',
  'reverse.sent.heading':
    'ጥያቄው ወደ ተልጋ ተልኳል',
  'reverse.sent.reference':
    'የጥያቄዎ ቁጥር፦',
  'reverse.sent.next':
    'ተልጋ ዋጋው ደንበኛው ጋር መድረሱን ያረጋግጣል። ያ እስኪጠናቀቅ ድረስ ወደ ቀሪ ሂሳብዎ ምንም አይመለስም።',
  'reverse.pending.notice':
    'ለዚህ ሽያጭ ጥያቄ አስቀድሞ ወደ ተልጋ ተልኳል። ሌላ አይላኩ።',
});

export const TABLES: Readonly<Record<Locale, Readonly<Partial<Record<MessageKey, string>>>>> =
  Object.freeze({ en: EN, am: AM });
