/**
 * Generate the Android shell's runtime configuration from `shell.config.json`.
 *
 * The shell has two places that must agree about which servers are reachable:
 * Capacitor's `allowNavigation`, which decides what the WebView opens in-app,
 * and the connect screen's validation, which decides what a merchant may type.
 * If they disagree in the permissive direction the merchant types an address,
 * the app hands it to the system browser, and Telga opens in a tab with no app
 * chrome — which is exactly where somebody would want a merchant typing a PIN.
 *
 * Rather than trust two hand-maintained lists to stay equal, `capacitor.config.ts`
 * reads the JSON directly and this script writes the same list into a
 * `www/config.js` the page loads. One source, two consumers, no drift.
 *
 * Run by `npm run mobile:configure`, and again by `mobile:sync` before every
 * `cap sync`, so a stale `config.js` cannot reach a build.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const mobile = join(here, '..', '..', 'apps', 'mobile');
const source = join(mobile, 'shell.config.json');
const target = join(mobile, 'www', 'config.js');

const config = JSON.parse(readFileSync(source, 'utf8'));

const hosts = config.allowedHosts;
if (!Array.isArray(hosts) || hosts.length === 0) {
  process.stderr.write(
    'shell.config.json must list at least one allowed host. An empty list would ' +
      'build an app that can never connect to anything.\n',
  );
  process.exit(2);
}

for (const host of hosts) {
  if (typeof host !== 'string' || host.trim() === '') {
    process.stderr.write(`Not a host: ${JSON.stringify(host)}\n`);
    process.exit(2);
  }
  // A bare `*` would allow every host on the internet, which defeats the
  // entire point of having this list. Refuse it here rather than let it reach
  // a signed build.
  if (host === '*' || host === '*.*') {
    process.stderr.write(
      `Refusing "${host}": a wildcard that matches every host means any link the ` +
        'app follows renders inside Telga\'s own chrome. Name the domains.\n',
    );
    process.exit(2);
  }
}

const defaultServer = config.defaultServer ?? null;
if (defaultServer !== null) {
  if (typeof defaultServer !== 'string' || !defaultServer.startsWith('https://')) {
    process.stderr.write('defaultServer must be null or an https:// URL.\n');
    process.exit(2);
  }
}

const banner =
  '/* GENERATED by scripts/mobile/configure-shell.mjs from shell.config.json.\n' +
  '   Do not edit: `npm run mobile:configure` overwrites this file. */\n';

const body =
  banner +
  'window.TELGA_SHELL = Object.freeze({\n' +
  `  allowedHosts: Object.freeze(${JSON.stringify(hosts)}),\n` +
  `  defaultServer: ${JSON.stringify(defaultServer)},\n` +
  `  supportContact: ${JSON.stringify(config.supportContact ?? 'MuleSoo Digital Services')},\n` +
  '});\n';

writeFileSync(target, body, 'utf8');

process.stdout.write(
  `Shell configured: ${String(hosts.length)} allowed host(s)` +
    `${defaultServer === null ? ', no default server' : `, default ${defaultServer}`}.\n`,
);
if (defaultServer === null) {
  process.stdout.write(
    'No default server, so the app opens on the connect screen and asks for an address.\n',
  );
}
