/**
 * The counter flow, as a controller.
 *
 * One object holds the whole merchant journey for a single sale: submit, watch,
 * settle. It owns the presentation state; it owns none of the domain state.
 *
 *   start(request)  → createSale, then hold whatever the server said
 *   watch()         → poll the transaction until it settles or the cap is hit
 *   view()          → the current view model, or the current screen condition
 *
 * ## Why the controller never decides an outcome
 *
 * Every method stores what the server returned and nothing else. There is no
 * branch here that turns a transport failure into a failed sale, or a settled
 * poll into a success; `toTransactionViewModel` reads the state the server sent
 * and the presentation table decides the rest. That is the guarantee the tests
 * exercise: an unreachable API leaves the transaction exactly where it was.
 */

import type {
  ApiEnvelope,
  CreateSaleBody,
  CreateSaleResultDto,
  RemoteData,
  Scheduler,
  TransactionDto,
  TransactionViewModel,
} from '@telga/pos-view-model';
import {
  PollController,
  fail,
  isTerminal,
  startLoad,
  succeed,
  toTransactionViewModel,
} from '@telga/pos-view-model';
import type { Locale } from '@telga/localization';
import { toRemoteFailure } from './apiClient';
import type { TrainingApiClient } from './apiClient';

export interface FlowOptions {
  readonly client: TrainingApiClient;
  readonly merchantId: string;
  readonly locale: Locale;
  readonly scheduler: Scheduler;
  now(): string;
  /** One correlation id per merchant action, generated by the caller. */
  newCorrelationId(): string;
  /** Called whenever the presentation state changes, so a view can re-render. */
  onChange?(state: RemoteData<TransactionDto>): void;
}

export class SaleFlow {
  private state: RemoteData<TransactionDto> = { status: 'IDLE' };
  private poll: PollController<TransactionDto> | undefined;
  private correlationId: string | undefined;
  private lastResult: CreateSaleResultDto | undefined;

  constructor(private readonly options: FlowOptions) {}

  get presentationState(): RemoteData<TransactionDto> {
    return this.state;
  }

  get saleResult(): CreateSaleResultDto | undefined {
    return this.lastResult;
  }

  get pollAttempts(): number {
    return this.poll?.attemptCount ?? 0;
  }

  get isPolling(): boolean {
    return this.poll?.isRunning ?? false;
  }

  /** Await the poll attempt currently in flight. Used by tests instead of a sleep. */
  async pollSettled(): Promise<void> {
    await this.poll?.settled();
  }

  private set(next: RemoteData<TransactionDto>): void {
    this.state = next;
    this.options.onChange?.(next);
  }

  /**
   * Submit a sale.
   *
   * A rejection — insufficient balance, provider unavailable, bad input — leaves
   * the flow in `ERROR` with no transaction, which is correct: no transaction
   * row was created either.
   */
  async start(body: CreateSaleBody): Promise<void> {
    this.correlationId = this.options.newCorrelationId();
    this.set(startLoad(this.state));

    const envelope = await this.options.client.createSale(body, this.correlationId);
    this.absorbSale(envelope);
  }

  private absorbSale(envelope: ApiEnvelope<CreateSaleResultDto>): void {
    if (!envelope.ok) {
      this.set(fail(this.state, toRemoteFailure(envelope, this.options.now())));
      return;
    }
    this.lastResult = envelope.data;
    if (envelope.data.transaction === null) {
      // A duplicate whose original row is not readable, or a rejection that
      // still returned ok. Neither is an outcome, so nothing is claimed.
      this.set(fail(this.state, {
        reasonCode: envelope.data.reasonCode ?? 'NO_TRANSACTION_RETURNED',
        messageKey: envelope.data.messageKey,
        status: null,
        correlationId: envelope.meta.correlationId,
        at: this.options.now(),
      }));
      return;
    }
    this.set(succeed(envelope.data.transaction, this.options.now()));
  }

  /** Read the transaction once. Used by the manual "check again now" action. */
  async refresh(): Promise<void> {
    const current = this.transactionId;
    if (current === undefined) return;
    this.set(startLoad(this.state));
    const correlationId = this.correlationId ?? this.options.newCorrelationId();
    const envelope = await this.options.client.getTransaction(
      this.options.merchantId,
      current,
      correlationId,
    );
    if (!envelope.ok) {
      this.set(fail(this.state, toRemoteFailure(envelope, this.options.now())));
      return;
    }
    this.set(succeed(envelope.data, this.options.now()));
  }

  get transactionId(): string | undefined {
    const data =
      this.state.status === 'READY' || this.state.status === 'STALE'
        ? this.state.data
        : this.state.status === 'LOADING'
          ? this.state.previous
          : undefined;
    return data?.transactionId;
  }

  /**
   * Poll until the transaction settles.
   *
   * The interval and the cap come from the server envelope, not from a constant
   * in this file — the POS asks at the rate the recovery worker actually works
   * at. A failed poll does not stop the loop and does not change the state on
   * screen beyond marking it stale.
   */
  watch(intervalMs: number, maxPolls: number): void {
    const id = this.transactionId;
    if (id === undefined) return;
    if (this.poll?.isRunning) return;

    this.poll = new PollController<TransactionDto>({
      intervalMs,
      maxPolls,
      scheduler: this.options.scheduler,
      fetchOnce: async () => {
        const correlationId = this.correlationId ?? this.options.newCorrelationId();
        const envelope = await this.options.client.getTransaction(
          this.options.merchantId,
          id,
          correlationId,
        );
        if (!envelope.ok) throw toRemoteFailure(envelope, this.options.now());
        return envelope.data;
      },
      onResult: (attempt) => {
        if (attempt.ok && attempt.value) {
          this.set(succeed(attempt.value, this.options.now()));
          return;
        }
        const failure = attempt.error as ReturnType<typeof toRemoteFailure>;
        this.set(fail(this.state, failure));
      },
      shouldContinue: (dto) => !isTerminal(dto.state),
    });
    this.poll.start();
  }

  stopWatching(): void {
    this.poll?.stop();
  }

  /** The view model, when there is a transaction to show. */
  view(): TransactionViewModel | undefined {
    const data =
      this.state.status === 'READY' || this.state.status === 'STALE'
        ? this.state.data
        : this.state.status === 'LOADING'
          ? this.state.previous
          : undefined;
    return data === undefined ? undefined : toTransactionViewModel(data, this.options.locale);
  }
}
